### PR TITLE
Issue #1, login model

### PR DESCRIPTION
**Pull request by Jlopezjlx**

### CODE REVIEW

**Comment by Jlopezjlx** [comment]
Done
1-deleted hub
2-Dockerfile added

**Comment by Jlopezjlx** [comment]
I did not make a docker compose file because I found that it is not neccesary at this moment because we only have one container running the app, but when we start using data bases and react, I'll do it a docker compose file

**Comment by Jlopezjlx** [comment]
login model working fine with some goog looking using css
Dockerfile to create an image of the project, also edit readme to add info how to run the project using docker

**Comment by KenanBek** [comment]
For future please try to keep PR per Issue with 1 commit. What I mean is:
- you want to solve issue let's say number #1111
- you create 1 PR
- with 1 commit inside
- if you need to add something new to the PR =
- you `amend` your commit (search for `git amend`)

For this PR it is ok to keep as it is.

**Comment by KenanBek** [comment]
Please add tests, unit tests for every functionality you add. As I said in our discussion group, for python-mentorship I can accept code without tests but for DevHub we will have strict rules.

**Comment by Jlopezjlx** [comment]
Got it

**Pull request closed without merging**
